#!/usr/bin/perl
use strict;
use warnings;
use Term::ANSIColor;

# Run the df command with human-readable sizes
my @df_output = `df -h`;
shift @df_output; # Remove the header line

# Print a custom header
print "\n";
print colored(['bold'], sprintf("%-20s %-10s %-10s %-10s %-8s %-s\n", 
    "Filesystem", "Size", "Used", "Available", "Use%", "Mounted on"));
print "=" x 80 . "\n";

# Process each line of output
foreach my $line (@df_output) {
    chomp $line;
    my ($filesystem, $size, $used, $avail, $percent, $mounted) = split(/\s+/, $line, 6);
    
    # Remove the % sign from the percent value
    $percent =~ s/%//;
    
    # Determine color based on usage percentage
    my $color = 'green';
    if ($percent >= 90) {
        $color = 'red';
    } elsif ($percent >= 75) {
        $color = 'yellow';
    }
    
    # Format and print the line with color
    printf "%-20s %-10s %-10s %-10s ", $filesystem, $size, $used, $avail;
    print colored([$color], sprintf("%-8s"), "$percent%");
    printf "%-s\n", $mounted;
}

print "\n";
