#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.
#
# Stolen from Mischa van Den Burg:
# https://github.com/mischavandenburg/dotfiles/blob/main/setup

# Create directories
# mkdir -p $HOME/.config/alacritty/themes
# mkdir -p $HOME/.config/starship
# mkdir -p $HOME/.config/kitty/themes

# Symbolic links
ln -sf $PWD/alacritty/alacritty.toml $HOME/.config/alacritty/alacritty.toml
#ln -sf $PWD/alacritty/themes/warlock.toml $HOME/.config/alacritty/themes/warlock.toml
# ln -sf $PWD/.bash_profile $HOME/.bash_profile
# ln -sf $PWD/.bashrc $HOME/.bashrc
ln -sf $PWD/tmux/.tmux.conf $HOME/.tmux.conf
ln -sf $PWD/vim/.vimrc $HOME/.vimrc
# ln -sf $PWD/vim/.vim/colors/tacme.vim $HOME/.vim/colors/tacme.vim
ln -sf $PWD/git/.gitconfig $HOME/.config/git/config
ln -sf $PWD/git/.gitignore_global $HOME/.config/git/gitignore_global
ln -sf $PWD/starship/starship.toml $HOME/.config/starship/starship.toml
ln -sf $PWD/kitty/kitty.conf $HOME/.config/kitty/kitty.conf
#ln -sf $PWD/mutt $HOME/.config/mutt
#ln -sf $PWD/lynx $HOME/.config/lynx
ln -sf $PWD/zsh/.zprofile $HOME/.zprofile
ln -sf $PWD/zsh/.zshrc $HOME/.config/zsh/.zshrc
ln -sf $PWD/wezterm/wezterm.lua $HOME/.config/wezterm/wezterm.lua
ln -sf $PWD/fd/ignore $HOME/.config/fd/ignore
ln -sf $PWD/rg/config $HOME/.config/rg/config
# ln -sf $PWD/rg/.rgignore $HOME/.config/rg/.rgignore
