#!/usr/bin/env bash
#
# Finds files in a current directory and opens in VIM.
# Opening in home folder (or another big directory) causes performance
# issues.
#
# TODO: Exclude more so that it could be used in big directories

set -o errexit
#set -o xtrace
set -o nounset

DIR="."
FZF_OPTS=(--preview 'bat -n --color=always {}' --preview-window=up,70%,wrap)
FD_OPTS=(--type f --hidden --follow '')

if [ $# -eq 1 ]; then
	echo "$1"
	DIR=$1
fi

FILE=$(fd "${FD_OPTS[@]}" "$DIR" | fzf "${FZF_OPTS[@]}") || exit

vim "$FILE"
