#!/usr/bin/env perl

use strict;
use warnings;

# Finds files in a current directory and opens in VIM.
# Opening in home folder (or another big directory) causes performance
# issues.
# The script depends on "igonore" file for the "fd" command in $HOME/.config/fd/ignore
# The ignore file speeds up searching in big directories eg. in $HOME
# The script assumes the vim, fd, fzf, and bat are installed on the system



# Default directory
my $DIR = ".";

# FZF options array
my @FZF_OPTS = (
    "--preview 'bat -n --color=always {}'",
    "--preview-window=up,70%,wrap"
);

# FD options array
my @FD_OPTS = (
    "--type f",
    "--hidden",
    "--follow",
    ""
);

# Check if directory argument is provided
if (@ARGV == 1) {
    print "$ARGV[0]\n";
    $DIR = $ARGV[0];
}

# Run fd and pipe to fzf, capture the selected file
my $fd_cmd = "fd " . join(" ", @FD_OPTS) . " " . quotemeta($DIR);
my $fzf_cmd = "fzf " . join(" ", @FZF_OPTS);

# Execute the command pipeline and get the selected file
my $FILE = `$fd_cmd | $fzf_cmd`;

# Exit if no file was selected (fzf returns non-zero)
exit if $? != 0 || !defined($FILE) || $FILE eq "";

# Remove trailing newline from fzf output
chomp($FILE);

# Open the file in vim
system("vim", $FILE);
