#!/usr/bin/env sh

# Setup the custom scripts

mkdir -p $HOME/.local/bin

ln -sf $PWD/gpt $HOME/.local/bin/gpt
ln -sf $PWD/bfu/bin/ff $HOME/.local/bin/ff
ln -sf $PWD/fs $HOME/.local/bin/fs

ln -sf $PWD/gdc $HOME/.local/bin/gdc
