#!/bin/bash

# A bash script that helps create notes in my zettelkasten folder

# prompt the user for a filename
get_filename() {
	filename=$1

	# check if filename is valid (one word or dash-separated, no .md
	#  extension)
	if [[ ! $filename =~ ^[A-Za-z0-9_-]+$ ]]; then
		echo "Invalid filename. Use only letters, numbers, underscores or dashes."
		exit 1
	fi

	# check if file already exists
	if [[ -f "$PKM/inbox/$filename.md" ]]; then
		echo "File '$filename.md' already exists. Choose a different
  name."
		exit 1
	fi

	echo $filename
}

# create and open a file in the specified directory
open_file() {
	dir=$1
	# create unique identifier
	timestamp=$(date +"%Y%m%d%H%M%S")
	# Create the file in the specified directory
	touch "$dir/$filename.md"
	# Remove the dashes and capitalize all words
	title=$( echo "$filename" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1' )

	# format the file
	{
		echo "# $title"
		echo -en "\n"
		echo "---"
		echo -en "\n"
		echo "tags:: "
		echo -en "\n"
		echo "---"
		echo -en "\n"
		echo -en "\n"
		echo -en "\n"
		echo -en "\n"
		echo "Links:"
		echo -en "\n"
		echo "$timestamp"
	} >>"$dir/$filename.md"

	# Open the file in Vim
	vim '+ normal 4jA' "$dir/$filename.md"
}

# check argument count
case $# in
0) filename=$(get_filename) ;; # No argument, prompt for filename
1)                             # One argument (filename), validate it
	filename=$1
	get_filename $filename
	;;
*) # More than one argument, print error
	echo "Provide only one filename separated by dashes, without .md extension."
	echo "Example: zet my-new-note"
	exit 1
	;;
esac

open_file "$PKM/inbox"
