#!/bin/bash

# Check if a directory is provided, if not default to the current
# directory
target_dir=${1:-.}

# Creates the target directory if it does not exist
mkdir -p "$target_dir"

# Loop through each markdown file with a hyphen in the filename
for file in *-*.md; do
	# The following Perl command splits the filename at the first
	# hyphen.  The regular expression /^(.*?)-(.*)$/ matches any number
	# of characters at the start of the string until it encounters the
	# first hyphen and captures it as the prefix. Similarly, it captures
	# the remaining part as the filename
	prefix=$(echo $file | perl -lne '($prefix, $filename) = /^(.*?)-(.*)$/;
    print $prefix')
	filename=$(echo $file | perl -lne '($prefix, $filename) = /^(.*?)-
    (.*)$/; print $filename')

	# Create new directory path using the prefix
	new_dir="$target_dir/$prefix"

	# Create the new directory if it doesn't exist
	mkdir -p "$new_dir"

	# Move the file to the new directory with its new name
	mv "$file" "$new_dir/$filename"
done
